# Generated by Django 4.1.3 on 2022-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andra-pradesh', 'Andra-pradesh'), ('Arunachal-pradesh', 'Arunachal-pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('chattisgarh', 'chattisgarh'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal-Pradesh', 'Himachal-Pradesh'), ('jharkhand', 'jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya-pradesh', 'Madhya-pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagalad'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil-nadu', 'Tamil-nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar-pradesh', 'Uttar-pradesh'), ('west-Bengal', 'west-Bengal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('I', 'Ittar'), ('P', 'Perfume'), ('D', 'Deoderant')], max_length=2),
        ),
    ]
